// Import required dependencies
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules"; // Built-in Node.js modules

// Define banner text that will be added to the bundled file
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Check if we're building for production based on command line argument
const prod = process.argv[2] === "production";

// Create esbuild context with configuration
const context = await esbuild.context({
	// Add banner to JavaScript output
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"], // Main entry point of the application
	bundle: true, // Bundle all dependencies into a single file
	// List of external dependencies that shouldn't be bundled
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins, // Spread all built-in Node.js modules
	],
	format: "cjs", // Output format as CommonJS
	target: "es2018", // Target ECMAScript version
	logLevel: "info", // Show info level logs during build
	sourcemap: prod ? false : "inline", // Generate source maps in development
	treeShaking: true, // Remove unused code
	outfile: "main.js", // Output file name
	minify: prod, // Minify code in production
});

// Handle production vs development builds
if (prod) {
	await context.rebuild(); // Build once for production
	process.exit(0); // Exit after build
} else {
	await context.watch(); // Watch for changes in development
}
